### PR TITLE
update live-common version

### PR DESCRIPTION
**Pull request by aulric-ledger**
update LLC version to 21.21.4

### CODE REVIEW

**Comment by gre** [comment]
unfortunately it breaks inside vercel it seems.

```
error @ledgerhq/live-common@21.21.4: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.7"
```

@valpinkman will have to look when available

**Comment by gre** [comment]
we actually have to upgrade more that this lib i feel; the last update is very old

**Comment by valpinkman** [comment]
Ok so I've taken a look. I tried to bump everything, but some APIs have changed too much in live-common (and with very few documentation). I guess we should peer-code @gre quickly when you come back, either that or we restart this project with a simpler stack, like nextjs

**Comment by valpinkman** [comment]
I've updated the node version to 14 in vercel. It should deploy now

**Pull request merged**
