### PR TITLE
Added live env editor

### PR DESCRIPTION
**Pull request by IAmMorrow**
added a live environment editor

### CODE REVIEW

**Comment by IAmMorrow** [comment]
I added some dependencies, do not hesitate to tell me if this is a problem.

**Comment by meriadec** [comment]
pretty cool :sunglasses:

**Comment by gre** [comment]
Pretty awesome! i've been testing it a bit (luckily with this netlify deploy preview)

Could you have some sort of expand/unexpand system in order for it to be unexpand by default? I would prefer we don't see it open initially because it's an advanced usage, also it can quickly eat too much space for the commands stuff :)
Maybe some kind of thin rectangle with a up and down triangle on top of the table?

Alternatively, this table edition could only be shown if you have no current transport? so it's hidden when there are commands? both ideas are possible.

Another UI feedback: I wonder if we should make it stick to the borders, not inside the left container padding, maybe this thing could be position:absolute 🤔 . just ideas, feel free to take or not ;)

In fact, it already seems to be absolute positioned:

Capture d’écran 2019-06-13 à 18 18 56



Also, to finish with feedback, it's probably we should whitelist what we really want to show as env, because many are not used by ledger-repl. but it's easy to add later. I imagine we just need: FORCE_PROVIDER, BASE_SOCKET_URL, DEVICE_PROXY_URL, EXPERIMENTAL_USB, MANAGER_DEV_MODE

**Comment by IAmMorrow** [comment]
@gre I added an "Advanced" section with a Hide / Show button. I believe we shouldn't hide it whenever there is a transport active as users might forget what settings they used and get confused (if they change it a lot).

It was not absolute positioned, but there was a strange flex bug on the upper section that made it look like it was (it behaved normally when there were no transport active)

I added a whitelist with the env var names you mentioned. It can easily be extended in the future.

**Comment by IAmMorrow** [comment]
@gre could you merge this :) ?

**Pull request merged**
